### ISSUE TITLE
support for responsive design?

### ISSUE THREAD

**Issue by shilik** [rigor789/nativescript-tailwind#17]
Hi @rigor789 

I wonder if nativescript-tailwind has the same support for responsive design like tailwind?
i.e
`<class="justify-start sm:justify-center md:justify-end lg:justify-between xl:justify-around ...">`

another question related with the above is how to make the element of the class dynamically.
for example.
I want to change the color dynamically under certain conditions.
from text-red-500 to text-white
what should I do in order to make it work?
Currently a workaround I can think of is to use :color="text_color" instead of using text-red-500 in the class.
Any suggestion? 

Regards.

**Comment by rigor789** [comment]
> I wonder if nativescript-tailwind has the same support for responsive design like tailwind?

No - media queries are stripped from the build because they are not (yet) supported in NativeScript. I had some ideas to retrofit them to NS, but never had the time to do so... It would involve processing the media queries, saving the different queries to an external file - converting all selectors to have a unique root-level prefix and applying these prefixes at runtime dynamically... It's not straight forward, so it may be better to implement actual media queries in NS at some point.

> change the color dynamically under certain conditions.

You can apply different classes in Vue based on conditions in multiple ways... What I would do is
```html
<Label :class="{ 'text-red-500 bg-red-200': error, 'text-green-500 bg-green-200': !error }" />
```
This will apply `text-red-500 bg-red-200` when `error` is true, and `text-green-500 bg-green-200` when it's false. You can add as many of these conditions as you like - just make sure you never dynamically assign parts of the class names like `text-${color}-500` because the new `purge` option cannot pick that up and will drop these classes.

**Comment by shilik** [comment]
Hi @rigor789 

Thank you very much for the possible solutions regarding responsive design as well as dynamical changing of the class elements. I have tried your proposed methods and it worked well. As tailwind is getting more and more popular, I am looking forward seeing the similar responsive design in the nativescript-tailwind soon sometime.

Thank you!
